### ISSUE TITLE
Remove outdated thumbnail sizes

### ISSUE THREAD

**Issue by codestylist** [wp-cli/media-command#198] opened 2024-05-12 17:59 UTC
I would like to request a feature to easily remove outdated image sizes without having to regenerate the thumbnails.

My situation is that I have a library of 32,000+ images, each image currently has up to 11 different thumbnail sizes. I have reduced the thumbnail sizes to 7, so four thumbnail sizes need to be deleted.

I would like to see a new parameter `wp media regenerate --only-deleting` added to simply delete all thumbnail sizes that are no longer needed. I know that `wp media regenerate` also does the job, but it also regenerates the already existing thumbnail files, which is not necessary in this case.

Hope my request makes sence for you. Thank you for all the work and time you put into wp-cli!

**Comment by swissspidy** [comment] 2024-05-12 20:46
Thanks for filing this feature request. This sounds like a duplicate of the second part of #111:

> Delete thumbnail files for old unregistered sizes in order to free up server space. This may result in broken images in your posts and pages.

**Closed by swissspidy** 2024-05-12 20:46 UTC

**Comment by swissspidy** [comment] 2024-05-13 08:06
I think so, yes, it sounds like a useful addition :) Maybe I'll even find time myself to look into it.

**Comment by codestylist** [comment] 2024-05-13 08:22
You are my hero 🥳. That would be really very useful! If you need someone to test it, please let me know. I would be more than happy to contribute something as well ☺️.

**Comment by swissspidy** [comment] 2024-05-13 12:10
#199 might do the trick.

**Comment by codestylist** [comment] 2024-05-13 19:35
You are awesome @swissspidy. I guess there is nothing I can help with, right?
Looking forward to have this implemented in the next version. Thank you very much for your time and effort!

**Comment by swissspidy** [comment] 2024-05-13 20:40
Feel free to test the PR and leave comments there :)
